doctrine:
    dbal:
        driver: 'pdo_mysql'  # 👈 explicitly use MySQL driver
        server_version: '8.0'  # 👈 adjust if you're using MariaDB (e.g. '10.11')
        url: '%env(resolve:DATABASE_URL)%'
        types:
            enum: Doctrine\DBAL\Types\StringType
        mapping_types:
            enum: string
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            driver: 'pdo_mysql'  # repeat here for test
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        dbal:
            driver: 'pdo_mysql'  # repeat here for prod
            server_version: '8.0'

        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
