framework:
    notifier:
        chatter_transports:
            mercure: '%env(MERCURE_DSN)%'
        texter_transports:
            infobip: '%env(INFOBIP_DSN)%'
        channel_policy:
            urgent: ['sms', 'email']
            high: ['sms', 'email']
            medium: ['sms', 'email']
            low: ['sms', 'email']
        admin_recipients:
            - { email: admin@example.com }