security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: user_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppLoginAuthenticator
            entry_point: App\Security\AppLoginAuthenticator
            logout:
                path: app_logout
                target: app_login
    access_control:
        - { path: ^/generate-hash, roles: PUBLIC_ACCESS }
        - { path: ^/create-test-user, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/user/new/front/athlete, roles: [ROLE_COACH, ROLE_ADMIN, ROLE_MED_STAFF] }
        - { path: ^/user/front/[0-9]+/edit, roles: [ROLE_COACH, ROLE_ADMIN, ROLE_MED_STAFF] }
        - { path: ^/user/front/athlete, roles: [ROLE_COACH, ROLE_ADMIN, ROLE_MED_STAFF] }
        - { path: ^/user/back/(coach|med_staff), roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/coach, roles: ROLE_COACH }
        - { path: ^/athlete, roles: ROLE_ATHLETE }
        - { path: ^/medical, roles: ROLE_MED_STAFF }
        - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
