vich_uploader:
    db_driver: orm

    mappings:
        injury_images:
            uri_prefix: /frontOffice/img
            upload_destination: '%kernel.project_dir%/public/frontOffice/img'
            namer: Vich\UploaderBundle\Naming\OrignameNamer