controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

calendar:
    resource: '../src/Controller/GoogleCalendarController.php'
    type: annotation

api_chart_data:
    path: /api/chart-data
    controller: App\Controller\Api\ChartApiController::chartData
    methods: GET

