# config/services.yaml
parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    app.profile_image_upload_dir: '%kernel.project_dir%/public/uploads/profile_images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Twilio Service
    App\Service\TwilioService:
        arguments:
            $sid: '%env(TWILIO_SID)%'
            $token: '%env(TWILIO_AUTH_TOKEN)%'

    # Explicit Finder service configuration
    Symfony\Component\Finder\Finder:
        class: Symfony\Component\Finder\Finder
        shared: false

    # Google calendar service 

    App\Service\GoogleCalendarService:
        arguments:
            $clientId: '%env(GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            $redirectUri: '%env(GOOGLE_REDIRECT_URI)%'
            $logger: '@logger'
    App\Controller\UserController:
        arguments:
            $csrfTokenManager: '@security.csrf.token_manager'
