parameters:
    elevenlabs.api_key: '%env(ELEVENLABS_API_KEY)%'
    huggingface.api_key: '%env(HUGGINGFACE_API_KEY)%'
    assemblyai.api_key: '%env(ASSEMBLYAI_API_KEY)%' # ✅ NEW

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Twilio Service
    App\Service\TwilioService:
        arguments:
            $sid: '%env(TWILIO_SID)%'
            $token: '%env(TWILIO_AUTH_TOKEN)%'

    # Explicit Finder service configuration
    Symfony\Component\Finder\Finder:
        class: Symfony\Component\Finder\Finder
        shared: false

    # Google Calendar Service
    App\Service\GoogleCalendarService:
        arguments:
            $clientId: '%env(GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            $redirectUri: '%env(GOOGLE_REDIRECT_URI)%'
            $logger: '@logger'

    # Mercure Hub service for publishing Turbo Streams
    Symfony\Component\Mercure\HubInterface: '@mercure.hub.default'

    # ElevenLabs TTS Service
    App\Service\ElevenLabsTTSService:
        arguments:
            $elevenLabsApiKey: '%elevenlabs.api_key%'

    # Hugging Face Sentiment Service
    App\Service\SentimentService:
        arguments:
            $huggingfaceApiKey: '%huggingface.api_key%'

    # Bad Words Detection Service
    App\Service\BadWordsService: ~

    # ✅ AssemblyAI Service
    App\Service\AssemblyAIService:
        arguments:
            $assemblyAiApiKey: '%assemblyai.api_key%'
            $logger: '@logger'
