# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Twilio Service
    App\Service\TwilioService:
        arguments:
            $sid: '%env(TWILIO_SID)%'
            $token: '%env(TWILIO_AUTH_TOKEN)%'

    # Explicit Finder service configuration
    Symfony\Component\Finder\Finder:
        class: Symfony\Component\Finder\Finder
        shared: false